-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, "%Y") YEAR, DATE_FORMAT(SALES_DATE, "%m") MONTH, GENDER, COUNT(DISTINCT O.USER_ID) USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3