-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT P, DOCTOR D, APPOINTMENT A
WHERE P.PT_NO = A.PT_NO
AND D.DR_ID = A.MDDR_ID
AND A.MCDP_CD = 'CS'
AND DATE_FORMAT(APNT_YMD, '%Y%m%d') = 20220413
AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD